### ISSUE TITLE
DataBaseAdapter test fails on 32-bit platforms

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusVector#9]
```
2: Test command: /usr/src/packages/BUILD/build/tests/database/src/testDatabaseAdapter
2: Test timeout computed to be: 9.99988e+06
2: error: sample vectors do not match
1/1 Test #2: DatabaseAdapter ..................***Failed    1.16 sec
```

**Comment by andreasbaumann** [comment]
Most likely numerical errors between 64-bit and 32-bit.

**Comment by patrickfrey** [comment]
I did a fix in strusBase of ByteOrder<uint64_t>::ntoh, ByteOrder<double>::ntoh respectively, that may have caused this problem.

**Comment by andreasbaumann** [comment]
problem persists:

https://build.opensuse.org/package/show/home:andreas_baumann/strusvector

I'll investigate with a debuger in the 32-bit OBS chroot..

**Comment by andreasbaumann** [comment]
Retested on FreeBSD 11.0 and 10.3 32-bit, works ok now.
